# ---- Base Node ----
FROM node:18.16.1-alpine3.17 AS base
# Set working directory
WORKDIR /usr/src/app
# Copy project file
COPY package*.json ./

# ---- Dependencies ----
FROM base AS dependencies
# Install production dependencies 
RUN npm ci



# ---- Copy Files/Build ----
FROM dependencies AS build 
# Copy app files
COPY . . 

# Build app
RUN npm run build 

# # Remove devDependencies
# RUN npm prune --production

# ---- Release ----
FROM base AS release 
# Copy production dependencies
COPY --from=dependencies /usr/src/app/node_modules ./node_modules
# Copy build files from build stage
COPY --from=build /usr/src/app/dist ./dist

# Expose port
EXPOSE 3000

# Define the command to run your app using CMD which defines your runtime
CMD ["node", "dist/src/main.js"]
