export const categories = [
    "Accounting",
    "Airport",
    "Amusement park",
    "Aquarium",
    "Art gallery",
    "Atm",
    "Bakery",
    "Bank",
    "Bar",
    "Beauty salon",
    "Bicycle store",
    "Book store",
    "Bowling alley",
    "Bus station",
    "Cafe",
    "Campground",
    "Car dealer",
    "Car rental",
    "Car repair",
    "Car wash",
    "Casino",
    "Cemetery",
    "Church",
    "City hall",
    "Clothing store",
    "Convenience store",
    "Courthouse",
    "Dentist",
    "Department store",
    "Doctor",
    "Drugstore",
    "Electrician",
    "Electronics store",
    "Embassy",
    "Fire station",
    "Florist",
    "Funeral home",
    "Furniture store ",
    "Gas station",
    "Gym",
    "Hair care",
    "Hardware store",
    "Hindu temple",
    "Home goods store",
    "Hospital",
    "Surance agency",
    "Jewelry store",
    "Laundry",
    "Lawyer",
    "Library",
    "Light rail station",
    "Liquor store",
    "Local government office",
    "Locksmith",
    "Lodging",
    "Meal delivery",
    "Meal takeaway",
    "Mosque",
    "Movie rental",
    "Movie theater",
    "Moving company",
    "Museum",
    "Night club",
    "Pater",
    "Park",
    "Parking",
    "Pet store",
    "Pharmacy",
    "Physiotherapist",
    "Plumber",
    "Police",
    "Post office",
    "Primary school",
    "Park",
    "Real estate agency",
    "Restaurants",
    "Roofing contractor",
    "School",
    "Secondary school",
    "Shoe store",
    "Shopping mall",
    "Spa",
    "Stadium",
    "Storage",
    "Store",
    "Subway station",
    "Supermarket",
    "Synagogue",
    "Taxi stand",
    "Tourist attraction",
    "Train station",
    "Transit station",
    "Travel agency",
    "University",
    "Veterary care",
    "Zoo",
    "Canteen",
    "Makeup stores",
    "Perfume shops",
    "Travel offices",
    "Sports tools",
    "traditional market",
    "Honey farm",
    "University department",
    "Education center",
    "Food and Beverage consultant",
    "Apartment Building",
    "Community Center",
    "Resort hotel",
    "Men clothing store",
    "Coffee Shop",
    "Chocolate shop",
    "Shopping Mall",
    "Plant nursery’s",
    "Contrition company",
    "Print shop",
    "Building design",
    "Language school",
    "Tribal headquarters",
    "Social club",
    "Nursery school",
    "Playground",
    "Mobile home dealer",
    "Hope store",
    "Custom home balder",
    "Corporate Office",
    "Grocery Stores",
    "Stationary Store",
    "Water purification",
    "Children’s amusement center",
    "Medical center",
    "2-star hotel",
    "3-star hotel",
    "4-star hotel",
    "5-star hotel",
    "General store",
    "Fruits and vegetable store",
    "Soup kitchen",
    "Event management company",
    "ternment cafe",
    "Farm",
    "Associated or organization",
    "Butcher shop",
    "Shrin",
    "Holiday apartment rental",
    "Juice shop",
    "Florist",
    "Candy store",
    "Warehouse",
    "Market",
    "Fruits wholesaler",
    "Prepare care",
    "Transportation services",
    "Home goods stores",
    "Mobile phone repair shop",
    "Glasses shop ",
    "Shoes shop",
    "Tailor",
    "Chinese market",
    "Boulevard",
    "Auto Accessories",
    "Wedding halls",
    "Dermatology clinic",
    "Wholesale market",
    "Gold market",
]